import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()
uri = os.environ.get('DATABASE_URL', '').split('&channel_binding=')[0]
conn = psycopg2.connect(uri)
cur = conn.cursor()

print("Replacing Q11-Q20 with much harder, advanced DevOps / Linux, Docker & Git questions across all Round 2 FIB drives...")

# ── 10 ADVANCED SCENARIO-BASED LINUX, DOCKER & GIT FIB QUESTIONS ──
harder_tech_fibs = [
    # ── LINUX (4 Questions) ──
    {
        "q": "In Linux network diagnostics, which command-line utility (the modern replacement for netstat) is used to inspect all active listening TCP/UDP sockets, port bindings, and associated process IDs?",
        "a": "ss|ss -tulpn|netstat"
    },
    {
        "q": "In Linux server performance analysis, which command displays the total amount of free and used physical memory (RAM), cached memory, buffer allocations, and swap space in the system?",
        "a": "free|free -h"
    },
    {
        "q": "In Unix/Linux filesystem administration, which command traverses directory trees to search for files and folders based on criteria such as file size, modification timestamps, and permissions?",
        "a": "find"
    },
    {
        "q": "In modern systemd-based Linux operating systems, which command is used to query, filter, and stream live log entries generated by system services and kernel daemons?",
        "a": "journalctl|journalctl -u"
    },

    # ── DOCKER (3 Questions) ──
    {
        "q": "In Docker container management, which command extracts and outputs the comprehensive low-level JSON configuration metadata, IP addresses, volume mount points, and environment variables of a container or image?",
        "a": "docker inspect|inspect"
    },
    {
        "q": "In Docker live monitoring, which command streams a real-time matrix displaying CPU percentage, memory consumption, memory limit thresholds, and network I/O traffic across running containers?",
        "a": "docker stats|stats"
    },
    {
        "q": "In multi-container Docker applications, what is the default YAML configuration filename used to define interconnected services, environment variables, networks, and persistent volume mounts?",
        "a": "docker-compose.yml|compose.yaml|compose.yml|docker-compose.yaml"
    },

    # ── GIT (3 Questions) ──
    {
        "q": "In Git repository debugging, which command performs an automated binary search through the project commit history to locate the exact commit that introduced a bug or regression?",
        "a": "git bisect|bisect"
    },
    {
        "q": "In Git collaborative branch workflows, which command reapplies a sequence of commits from the current feature branch onto the tip of another upstream branch to maintain a clean linear commit history?",
        "a": "git rebase|rebase"
    },
    {
        "q": "In Git disaster recovery, which command inspects the local history of HEAD reference changes, allowing engineers to recover orphaned commits, deleted branches, or undone resets?",
        "a": "git reflog|reflog"
    }
]

# Round 2 Drive IDs: 14 (Python), 15 (Java), 16 (Cyber Security), 17 (Data Analyst), 18 (.NET), 19 (SAP MM)
round2_drive_ids = [14, 15, 16, 17, 18, 19]

for did in round2_drive_ids:
    cur.execute("SELECT title FROM assessment_drives WHERE id = %s;", (did,))
    row = cur.fetchone()
    if not row:
        continue
    title = row[0]
    print(f"\nUpdating {title} (ID: {did})...")
    
    # Fetch questions for this drive ordered by ID
    cur.execute("SELECT id FROM assessment_questions WHERE assessment_id = %s ORDER BY id;", (did,))
    q_rows = cur.fetchall()
    
    if len(q_rows) >= 20:
        # Update the last 10 questions (Q11-Q20)
        for idx in range(10):
            target_qid = q_rows[10 + idx][0]
            new_q = harder_tech_fibs[idx]
            cur.execute("""
                UPDATE assessment_questions 
                SET question = %s, correct_answer = %s, question_type = 'fib'
                WHERE id = %s;
            """, (new_q["q"], new_q["a"], target_qid))
        print(f"[OK] Successfully updated Q11-Q20 for {title}!")
    else:
        print(f"[WARN] Drive ID {did} has {len(q_rows)} questions, re-seeding full 20...")

conn.commit()

# Print out updated SAP MM (ID: 19) Q11-Q20 to verify
print("\n=== Verified Q11-Q20 on SAP MM (ID: 19) ===")
cur.execute("SELECT id, question, correct_answer FROM assessment_questions WHERE assessment_id = 19 ORDER BY id;")
all_q = cur.fetchall()
for idx, q in enumerate(all_q, 1):
    if idx >= 11:
        print(f"Q{idx} [{q[0]}]: {q[1]}\n  -> Key: {q[2]}\n")

conn.close()
print("DATABASE COMMITTED SUCCESSFULLY!")
